// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJMNiCRykXZEeCRTFHfkoXk6Pw-dmRC18',
    appId: '1:1029169788614:web:d114810b021e137a1dc9c7',
    messagingSenderId: '1029169788614',
    projectId: 'quran-app-2062d',
    authDomain: 'quran-app-2062d.firebaseapp.com',
    storageBucket: 'quran-app-2062d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF0uWhTBQmBLXYL2t52Ql_80tN4JHxwsI',
    appId: '1:1029169788614:android:cc1e7c89cd05043f1dc9c7',
    messagingSenderId: '1029169788614',
    projectId: 'quran-app-2062d',
    storageBucket: 'quran-app-2062d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvTg-gxcPPsFQB8TgUWVJ20P3sjDIVhj0',
    appId: '1:1029169788614:ios:6c598eecf85395d31dc9c7',
    messagingSenderId: '1029169788614',
    projectId: 'quran-app-2062d',
    storageBucket: 'quran-app-2062d.appspot.com',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvTg-gxcPPsFQB8TgUWVJ20P3sjDIVhj0',
    appId: '1:1029169788614:ios:b4d17e3a588a7c511dc9c7',
    messagingSenderId: '1029169788614',
    projectId: 'quran-app-2062d',
    storageBucket: 'quran-app-2062d.appspot.com',
    iosBundleId: 'com.example.quranApp.RunnerTests',
  );
}
